from setuptools import find_packages
from setuptools import setup

setup(name='r2pa',
      version='0.1.0',
      description='R2PA',
      long_description='',
	  author='Timo Nolle, Yannik Klein',
      author_email='timonolle@gmail.com, yannik.klein@hotmail.com',
      url='https://github.com/tnolle/r2pa',
      license='GPL-3.0',
      requires=[
            # 'arrow',
            # 'flask',
            # 'flask-compress',
            # 'flask-cors',
            # 'flask_sqlalchemy_session',
            # 'h5py',
            # 'hmmlearn',
            # 'joblib',
            # 'keras',
            # 'lxml',
            # 'matplotlib',
            # 'networkx',
            # 'numpy',
            # 'openpyxl',
            # 'pandas',
            # 'pydot',
            # 'pygraphviz',
            # 'pyodbc',
            # 'scikit-learn',
            # 'scipy',
            # 'seaborn',
            # 'sqlalchemy',
            # 'tensorflow',
            # 'tqdm',
            # 'tqdm',
            # 'untangle',
            # 'xlrd',
      ],
      packages=find_packages())